table EDGE
	lineageTag: 2e5626bf-b0cc-44cc-abae-248576a4d0eb

	measure 'link_mass average per type_cde' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('EDGE'[type_cde])),
				CALCULATE(SUM('EDGE'[link_mass]))
			)
		formatString: 0
		lineageTag: f82a402f-9966-43a8-921d-b31b6fe424f2

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "AveragePerCategory"
				}

		changedProperty = FormatString

	column from_node_id
		dataType: string
		lineageTag: 9b413277-0aee-4661-b93b-fc7b06f426ec
		summarizeBy: none
		sourceColumn: from_node_id

		annotation SummarizationSetBy = Automatic

	column to_node_id
		dataType: string
		lineageTag: 13cd6be5-7c91-41ce-b77d-dfa52928989d
		summarizeBy: none
		sourceColumn: to_node_id

		annotation SummarizationSetBy = Automatic

	column descriptor
		dataType: string
		lineageTag: 943727da-f15f-4985-9410-9f611ddbafef
		summarizeBy: none
		sourceColumn: descriptor

		annotation SummarizationSetBy = Automatic

	column type_cde
		dataType: string
		lineageTag: 03f51c40-823c-4688-bb17-70b81365a8e6
		summarizeBy: none
		sourceColumn: type_cde

		annotation SummarizationSetBy = Automatic

	column link_mass
		dataType: int64
		formatString: 0
		lineageTag: 4cc025b5-fb9d-42f5-a430-a5df8d248ca7
		summarizeBy: sum
		sourceColumn: link_mass

		annotation SummarizationSetBy = Automatic

	partition EDGE = m
		mode: import
		source =
				let
				    Source = Json.Document(Web.Contents("https://hfunworrmdfxzdtmbvth.supabase.co/rest/v1/edges?select=*", [Headers=[#"Content-Type"="application/json", Accept="application/json", apikey="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmdW53b3JybWRmeHpkdG1idnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwOTE1MzUsImV4cCI6MjA4MTY2NzUzNX0.lUOR-J6qY-EyjCQv9tPh83mBzdIRq7pCIzstOP7xktU", Authorization="Bearer: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmdW53b3JybWRmeHpkdG1idnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwOTE1MzUsImV4cCI6MjA4MTY2NzUzNX0.lUOR-J6qY-EyjCQv9tPh83mBzdIRq7pCIzstOP7xktU"]])),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"from_node_id", "to_node_id", "descriptor", "type_cde", "link_mass"}, {"from_node_id", "to_node_id", "descriptor", "type_cde", "link_mass"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"from_node_id", type text}, {"to_node_id", type text}, {"descriptor", type text}, {"type_cde", type text}, {"link_mass", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

